Mon 15 Apr 2024 08:16:06 PM EDT
Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/test-source-container.yaml b/tasks/test-source-container.yaml
--- a/tasks/test-source-container.yaml
+++ b/tasks/test-source-container.yaml
@@ -27,7 +27,20 @@ spec:
           #sourceContainer=${containerImage}-source
           git_sha=$(jq -r '.source.git.revision' <<< $component)
           echo $git_sha
-          sourceContainer="${containerImage%@sha256:*}:on-pr-${git_sha}.src"
+          tags=$(skopeo list-tags ${containerImage%@sha256:*} | jq -r .Tags[])
+          for tag in $tags
+          do
+            if [ $tag == "on-pr-${git_sha}.src" || $tag == "${git_sha}.src" ]; then
+              echo "found tag: $tag"
+              sourceContainer="${containerImage%@sha256:*}:$tag"
+              break
+            fi
+          done
+          if [ -z "${sourceContainer}" ] ; then
+            echo "Error: source container tag not found"
+            exit 1
+          fi
+
           echo $sourceContainer
           mkdir /tmp/$$
           skopeo copy docker://$sourceContainer dir:/tmp/$$
